// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/extend.h"
#include "Commands/retract.h"
#include "Commands/rotateIn.h"
#include "Commands/rotateOut.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    joystick2.reset(new Joystick(1));
    
    joystickButton4.reset(new JoystickButton(joystick2.get(), 2));
    joystickButton4->WhileHeld(new retract());
    joystickButton2.reset(new JoystickButton(joystick2.get(), 1));
    joystickButton2->WhileHeld(new rotateIn());
    joystick1.reset(new Joystick(0));
    
    joystickButton3.reset(new JoystickButton(joystick1.get(), 2));
    joystickButton3->WhileHeld(new extend());
    joystickButton1.reset(new JoystickButton(joystick1.get(), 1));
    joystickButton1->WhileHeld(new rotateOut());

    // SmartDashboard Buttons
    SmartDashboard::PutData("retract", new retract());
    SmartDashboard::PutData("extend", new extend());
    SmartDashboard::PutData("rotateIn", new rotateIn());
    SmartDashboard::PutData("rotateOut", new rotateOut());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getJoystick1() {
   return joystick1;
}

std::shared_ptr<Joystick> OI::getJoystick2() {
   return joystick2;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
